substitutions:
  _APP_DIR: devops

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'python:3.12'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        cd "${_APP_DIR}"
        python -V
        pip install -r requirements.txt
        # you have a tests/ run it
        # pytest -q
        echo "=====CI passed====="
