substitutions:
  _SERVICE_NAME: python-app
  _REGION: us-east4
  _AR_REPO: python-app-image
  _IMAGE_NAME: app-image

steps:
  # 0) sanity check: make sure Dockerfile exists in the fetched source
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🔎 Checking files in /workspace..."
        ls -la
        echo "🔎 Checking python-app/ ..." > output/info.txt
        ls -la python-app
        test -f python-app/Dockerfile
        echo "✅ Dockerfile exists" > output/info.txt

  # 1) Build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🚀 [STEP 1] Building Docker image..." > output/info.txt
        docker build -t us-east4-docker.pkg.dev/gcp-devops-ma2026/python-app-image/app-image:v2 python-app
        echo "✅ [STEP 1] Build complete" > output/info.txt

artifacts:
  objects:
    location: 'gs://my-build-artifacts-bucket/artifacts-demo/'
    paths:
      - ['dist/output/info.txt'] 


options:
  logging: CLOUD_LOGGING_ONLY
